
name: 'Exotic Action'
description: 'Download exotic libraries into your C/C++ GitHub Action environment. Also, run regression testing with cester.'

inputs:
    
  download-exotic-libraries: 
    description: 'If false the exotic libraries will not be downloaded'
    required: false
    default: true
    
  run-cester-regression: 
    description: 'If false skip running the test files under test folders'
    required: false
    default: true
    
  test-folders: 
    description: 'Array of folders to run cester regression test in.'
    required: false
    default: |
        test/
    
  test-file-pattern: 
    description: 'A regex pattern to match the file to run in each of the provided test folder'
    required: false
    default: |
        ^test_
        _test[.c](c\+\+|cpp|c)
    
  test-exclude-file-pattern: 
    description: 'A regex pattern to match the file to exclude from execution in each of the provided test folder'
    required: false
    default: |
        mock+
    
  compiler-options-for-tests: 
    description: 'Array of compiler options to add when compiling each test file'
    required: false
    default: |
        -pedantic
    
  cester-options: 
    description: 'If false skip running the test files under test folders'
    required: false
    default: |
        --cester-verbose
        --cester-nomemtest
    
  install-compilers:
    description: 'Specify which compiler to install in the environment regardless of the compiler selected in the matrix'
    required: false
    default:      
    
  the-matrix-compiler-internal-use-only: 
    description: 'The compiler to use to run the regression tests. Note: do not change the value in workflow yml.'
    required: false
    default: ${{ matrix.compiler }}
    
  the-matrix-arch-internal-use-only: 
    description: 'The current architecture this workflow is taking place. Note: do not change the value in workflow yml.'
    required: false
    default: ${{ matrix.platform }}
    
outputs:
  tests-passed:
    description: 'true if the cester regression test passed'
    
runs:
  using: 'node12'
  main: 'dist/index.js'
  
  
  