
name: Build dist/index.js

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:            
  build-dist:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        
      - name: Download NPM Dependencies and Build 🔧
        run: |
          if [ "dist/index.js" -nt "index.js" ]; then exit 0; else echo "You need to compile index.js 'ncc build index.js'"; exit 1; fi
        
